### ISSUE TITLE
Allow running multiple Leeway scripts in parallel

### ISSUE THREAD

**Issue by mads-hartmann** [gitpod-io/leeway#136]
We're currently using Leeway scripts to create preview environments in `gitpod-io/gitpod`. Currently we have the following sequential invocations of `leeway run`. This is leaving some parallelism on the table.

```
leeway run dev/preview:create-preview
leeway run dev/preview:build
previewctl install-context
leeway run dev/preview:deploy-gitpod
leeway run dev/preview:deploy-monitoring-satellite
```

Ideally `create-preview` and `build` would run in parallel. Then we'd wait for `install-context`, and then run `deploy-gitpod` and `deploy-monitoring-satellite` in parallel.

I did a [quick prototype](https://github.com/gitpod-io/gitpod/pull/14857) to add parallelism through the use of ephemeral packages and dependencies between them. It works. But controlling parallelism this way in YAML really isn't nice. I find it hard to read and it takes a while to parse where the "forks and joins" are happening. Even if we allowed scripts to have dependencies on scripts, we'd still have to express the parallel execution in YAML.

I'd prefer to extend leeway such that you can pass multiple scripts to `leeway run`. Our implementation would then be:

```
leeway run dev/preview:create-preview dev/preview:build
previewctl install-context
leeway run dev/preview:deploy-gitpod dev/preview:parallel-deploy-all
```

**Comment by csweichel** [comment]
Both options (inter-script dependencies and multiple args to `run`) are nicely orthogonal. Given the very low complexity of enabling `run <script1> <script2>`, and the nice affordance this produces, this is the way.

We would want to note in the long description of the `run` command that multiple scripts will be executed in parallel.

**Comment by meysholdt** [comment]
I like the simplicity of passing multiple scripts to `leeway run`. 

How would you format logs? 
Would there be an additional level of `[xx]` prefixes on top of the ones our nested call of `leeway build` already generates? 
E.g. `leeway run dev/preview:create-preview dev/preview:build` would output
```
[dev/preview:build][component1] Building....
[dev/preview:build][component2] Building....
[dev/preview:create-preview] Terraform init...
[dev/preview:build][component2] Building....
[dev/preview:create-preview] Terraform apply...
```

When we discussed parallelism in the past, I did have another solution in mind: Make the executable element part of the build graph, so Leeway could decide parallelism based on dependencies, just like it does with packages today. However, if we can get away with a simpler solution, I'm all for it.

**Comment by csweichel** [comment]
> Would there be an additional level of [xx] prefixes on top of the ones our nested call of leeway build already generates?

I would not think so.
There is the opportunity for one harmonised build beforehand though, i.e. instead of building many different `_deps` packages, build one single one.
