### ISSUE TITLE
'leeway vat --ingore-warning' returns false positives

### ISSUE THREAD

**Issue by geropl** [gitpod-io/leeway#47]
Example: https://werft.gitpod-dev.com/job/gitpod-build-gpl-test.1/logs#build:build
(the output at the top is from an ignored `leeway vat --ingore-warning`.).

One of the error messages:
`time="2021-01-21T09:36:09Z" level=error msg="gitpod-core/components/ws-daemon-api/go:lib: Go package does not have go package config"`
The build later runs fine, though.

To reproduce: run `leeway vet --ignore-warnings` in the gitpod-io/gitpod repo.

The check: https://github.com/gitpod-io/leeway/commit/42ce465e51ea494450dcf84c7a01c6b9fb87c833#diff-018cf017b8fa7d438ced439fa3d022e22d062478f60f46cad88ff79d3217149bR53-R56
The commit that introduced it: https://github.com/gitpod-io/leeway/commit/42ce465e51ea494450dcf84c7a01c6b9fb87c833

**Comment by AlexTugarev** [comment]
Is it fixed in https://github.com/gitpod-io/leeway/commit/cb49e6c4b0cee38884aa78f0782d667af6d3ad7d?

**Comment by geropl** [comment]
> Is it fixed in cb49e6c?

Absolutely.
