### ISSUE TITLE
Does not run on macOS

### ISSUE THREAD

**Issue by all-the-hackz** [gitpod-io/leeway#50]
README says "Leeway assumes its running on Linux or macOS"

While it might assume that, it doesn't actually run on OS X since it [uses "cp --parents"](https://github.com/gitpod-io/leeway/blob/6bea0e41e76f0ec22901a1cfc062e385a8ea2a0f/pkg/leeway/build.go#L550) which is not supported on OS X - it fails with "illegal option" errors i.e. a BSD/GNU issue.

As no-one has reported this for the >2yrs that option has been in the code base the simplest option may be to remove that statement from the README and say it only runs on Linux?

While it might be possible to suggest people install the [GNU fileutils](https://apple.stackexchange.com/questions/69223/how-to-replace-mac-os-x-utilities-with-gnu-core-utilities) this has other potential drawbacks.
 
Alternatively, Swift/T hit a similar issue some time ago, resulting in [this workaround](https://github.com/swift-lang/swift-t/blob/master/turbine/code/maint/cp-parents.sh) so something similar could be added, but probably not worth the effort in maintaining parity.

Thoughts?

**Comment by aledbf** [comment]
Please check the latest version.
