### ISSUE TITLE
command which prints build directory

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/leeway#64]
I would like to know where next build will stored, it would be nice to have a command which prints it, i.e.

```
leeway build dir "myapp:mypackage"
/tmp/build/myapp.mypackage.abcd
```

**Comment by akosyakov** [comment]
I used something like `leeway describe "//:init" -t "/tmp/build/{{ .Metadata.Name }}.{{ .Metadata.Version }}"` for now, but it is rather close, since we transform name to be valid dir name

**Comment by csweichel** [comment]
`leeway describe "//:init" -t "/tmp/build/{{ .Metadata.FilesystemSafeName }}.{{ .Metadata.Version }}"` not prints the correct name
